### PR TITLE
Fixes to get the simulation to work with the current HEAD

### PR DESCRIPTION
**Pull request by shankari**
The changes are outlined in https://github.com/US-JOET/base-camp/issues/153#issuecomment-2161931501

### CODE REVIEW

**Comment by shankari** [comment]
After creating the PR, re-ran the command again and then charged again.
Got the same results as https://github.com/US-JOET/everest-demo/pull/4/commits/11a1a909df7247fedd2cdb30a2ef024a1959678e

**Comment by shankari** [comment]
Testing done:
- Modified `demo-iso15118-2-ac-plus-ocpp.sh` to copy instead of clone
- `bash demo-iso15118-2-ac-plus-ocpp.sh -r .../everest-demo -3`
- Selected AC ISO 15118; worked
- Selected AC ISO 15118 PnC; worked

However, the detailed ISO logging isn't showing up. fixing that...

**Comment by shankari** [comment]
Fixed. Now tried to call `setChargingProfile`, which failed with the following error. it looks like @louisg1337 fixed MaEVe 😄 
Fixing this in the patch for now and will ask @louisg1337 to test by removing the patch tomorrow.

```
2024-06-13 03:38:11.473557 [ERRO] ocpp:OCPP201    void ocpp::v201::from_json(const json&, SetChargingProfileRequest&) :: In the message class, parsing from JSON: {"ChargingProfile":{"chargingProfileKind":"Absolute","chargingProfilePurpose":"TxDefaultProfile","chargingSchedule":[{"chargingRateUnit":"A","chargingSchedulePeriod":[{"limit":20,"numberPhases":1,"startPeriod":0}],"duration":86400,"id":0,"minChargingRate":0,"startSchedule":"2024-06-12T00:00:00.000Z"}],"id":1,"recurrencyKind":"Daily","stackLevel":1},"EvseId":0}
2024-06-13 03:38:11.473955 [ERRO] ocpp:OCPP201    void ocpp::v201::ChargePoint::message_callback(const std::string&) :: JSON exception during handling of message: [json.exception.out_of_range.403] key 'ChargingProfileType' not found
```

**Comment by shankari** [comment]
Everything seems to work now. @louisg1337 can you pull from this branch, run and verify that you get the same results? I can then merge this to the `charin-e2e-demo` branch so that AFS can build on it. Then finally, we can start removing the patches one by one by incorporating the changes into the actual code 😄 

Testing done:

<details>
<summary>Plugged in the car and got a charge delivery of 22kW with a 230V and 32 A</summary>

```
[DEBG] iso15118_car    pybind11_init_everestpy(pybind11::module_&)::<lambda(const std::string&)> :: Decoded message (ns=urn:iso:15118:2:2013:MsgDef): {"V2G_Message":{"Header":{"SessionID":"67634FE7DDFF935F"}
"Body":{"ChargeParameterDiscoveryRes":{"ResponseCode":"OK"
"EVSEProcessing":"Finished"
"SAScheduleList":{"SAScheduleTuple":[{"SAScheduleTupleID":1
"PMaxSchedule":{"PMaxScheduleEntry":[{"RelativeTimeInterval":{"start":0
"duration":86400}
"PMax":{"Multiplier":0
"Unit":"W"
"Value":22080}}]}}]}
"AC_EVSEChargeParameter":{"AC_EVSEStatus":{"NotificationMaxDelay":0
"EVSENotification":"None"
"RCD":false}
"EVSENominalVoltage":{"Multiplier":-1
"Unit":"V"
"Value":2300}
"EVSEMaxCurrent":{"Multiplier":-1
"Unit":"A"
"Value":320}}}}}}
```

</details>

<details>
<summary>Unplugged the car, and set a profile that was valid starting `2024-06-13T00:00:00.000Z` and a limit of 20 A (the file is attached)</summary>

```
2024-06-13 03:52:58.408417 [ERRO] ocpp:OCPP201    void ocpp::v201::ChargePoint::handle_set_charging_profile_req(ocpp::Call<ocpp::v201::SetChargingProfileRequest>) :: Received SetChargingProfile: {
    "chargingProfile": {
        "chargingProfileKind": "Absolute",
        "chargingProfilePurpose": "TxDefaultProfile",
        "chargingSchedule": [
            {
                "chargingRateUnit": "A",
                "chargingSchedulePeriod": [
                    {
                        "limit": 20.0,
                        "numberPhases": 1,
                        "startPeriod": 0
                    }
                ],
                "duration": 86400,
                "id": 0,
                "minChargingRate": 0.0,
                "startSchedule": "2024-06-13T00:00:00.000Z"
            }
        ],
        "id": 1,
        "recurrencyKind": "Daily",
        "stackLevel": 1
    },
    "evseId": 1
}
with messageId: 2b9f7b12-ac9b-46b8-88a3-72327a66928b
2024-06-13 03:52:58.409520 [WARN] ocpp:OCPP201    module::OCPP201::ready()::<lambda()> :: Received a new Charging Schedules from the CSMS or another actor.
2024-06-13 03:52:58.409682 [INFO] ocpp:OCPP201     :: ProfileId #1 Kind: Absolute
2024-06-13 03:52:58.409723 [INFO] ocpp:OCPP201     :: #1 find_period_at> 2024-06-13T00:00:00.000Z
2024-06-13 03:52:58.409765 [INFO] ocpp:OCPP201     ::    find_period_at>        start_time> 2024-06-13T03:52:58.409Z
2024-06-13 03:52:58.409794 [INFO] ocpp:OCPP201     ::    find_period_at> period_start_time> 2024-06-13T00:00:00.000Z
2024-06-13 03:52:58.409821 [INFO] ocpp:OCPP201     ::    find_period_at>   period_end_time> 2024-06-14T00:00:00.000Z
2024-06-13 03:52:58.409929 [INFO] ocpp:OCPP201     :: PeriodDateTimePair>  period: {
    "limit": 20.0,
    "numberPhases": 1,
    "startPeriod": 0
} end_time: 2024-06-14T00:00:00.000Z
2024-06-13 03:52:58.409998 [INFO] ocpp:OCPP201     :: period.has_value() limit = 4600
2024-06-13 03:52:58.410040 [INFO] ocpp:OCPP201     :: period.has_value() stackLevel = 4600
2024-06-13 03:52:58.453739 [ERRO] ocpp:OCPP201    void ocpp::v201::ChargePoint::handle_set_charging_profile_req(ocpp::Call<ocpp::v201::SetChargingProfileRequest>) :: Received profile validity: Validsetting response to {
    "status": "Accepted"
}
```

</details>

<details>
<summary>Plugged in the car again, and got max power of 4600 W, with 230V and 6.6A</summary>

```
[DEBG] iso15118_car    pybind11_init_everestpy(pybind11::module_&)::<lambda(const std::string&)> :: Decoded message (ns=urn:iso:15118:2:2013:MsgDef): {"V2G_Message":{"Header":{"SessionID":"6F6CE6DFFD1F6169"}
"Body":{"ChargeParameterDiscoveryRes":{"ResponseCode":"OK"
"EVSEProcessing":"Finished"
"SAScheduleList":{"SAScheduleTuple":[{"SAScheduleTupleID":1
"PMaxSchedule":{"PMaxScheduleEntry":[{"RelativeTimeInterval":{"start":0
"duration":86400}
"PMax":{"Multiplier":0
"Unit":"W"
"Value":4600}}]}}]}
"AC_EVSEChargeParameter":{"AC_EVSEStatus":{"NotificationMaxDelay":0
"EVSENotification":"None"
"RCD":false}
"EVSENominalVoltage":{"Multiplier":-1
"Unit":"V"
"Value":2300}
"EVSEMaxCurrent":{"Multiplier":-1
"Unit":"A"
"Value":66}}}}}}
```

</details>

[TXProfile_1.json](https://github.com/user-attachments/files/15813525/TXProfile_1.json)

**Comment by louisg1337** [comment]
To do my testing, I clone the `US-JOET/everest-demo` repo and checked out `charin-e2e-demo-last-min-hacks`. I then deleted all previous docker containers I had and ran `bash demo-iso15118-2-ac-plus-ocpp.sh -3`.

> Plugged in the car and got a charge delivery of 22kW with a 230V and 32 A

Got the same result when plugging in the car normally.
```
2024-06-13 15:03:56.582203 [DEBG] iso15118_car    pybind11_init_everestpy(pybind11::module_&)::<lambda(const std::string&)> :: Decoded message (ns=urn:iso:15118:2:2013:MsgDef): {"V2G_Message":{"Header":{"SessionID":"9FAA4FDD3FEFBD3F"},
"Body":{"ChargeParameterDiscoveryRes":{"ResponseCode":"OK",
"EVSEProcessing":"Finished",
"SAScheduleList":{"SAScheduleTuple":[{"SAScheduleTupleID":1,
"PMaxSchedule":{"PMaxScheduleEntry":[{"RelativeTimeInterval":{"start":0,
"duration":86400},
"PMax":{"Multiplier":0,
"Unit":"W",
"Value":22080}}]}}]},
"AC_EVSEChargeParameter":{"AC_EVSEStatus":{"NotificationMaxDelay":0,
"EVSENotification":"None",
"RCD":false},
"EVSENominalVoltage":{"Multiplier":-1,
"Unit":"V",
"Value":2300},
"EVSEMaxCurrent":{"Multiplier":-1,
"Unit":"A",
"Value":320}}}}}}
```

> Unplugged the car, and set a profile that was valid starting `2024-06-13T00:00:00.000Z` and a limit of 20 A (the file is attached)

I unfortunately was not able to reproduce the `setChargingProfile` working properly. I ran the `setChargingProfile` script we have with the JSON file, but there weren't any EVerest logs that indicated we received a new profile. I did check the OCPP logs, however, and I found the `setChargingProfile` requests there, but with the typical "Unknown" response we have always gotten. 

Screenshot 2024-06-13 at 11 21 17 AM

I'm not sure if I am doing something wrong, or if I don't have an updated version of EVerest with the new `chargingProfile` implementation. I'll keep on messing around with it to see what I am doing wrong that i am not getting the same results. 

> Plugged in the car again, and got max power of 4600 W, with 230V and 6.6A

Unable to reproduce because of the above.



**EDIT:** I think I realize why. When applying the patches I kept on getting "xxx.patch file not found", which is because I wasn't running the script with my local version of `everest-demo`. I'll run the tests again, this time using my local version, and record the results.

**Comment by louisg1337** [comment]
**Updated Testing**

As I said in the edit section above, I was running the script without pointing it to my local directory, so I wasn't getting any of the patches. Now that I have the patches, things are working as expected.

> Plugged in the car and got a charge delivery of 22kW with a 230V and 32 A

Same as the comment above.

> Unplugged the car, and set a profile that was valid starting 2024-06-13T00:00:00.000Z and a limit of 20 A (the file is attached)

<details>
<summary>Got the same response after setChargingProfile API call</summary>

```
2024-06-13 16:28:32.924613 [ERRO] ocpp:OCPP201    void ocpp::v201::ChargePoint::handle_set_charging_profile_req(ocpp::Call<ocpp::v201::SetChargingProfileRequest>) :: Received SetChargingProfile: {
    "chargingProfile": {
        "chargingProfileKind": "Absolute",
        "chargingProfilePurpose": "TxDefaultProfile",
        "chargingSchedule": [
            {
                "chargingRateUnit": "A",
                "chargingSchedulePeriod": [
                    {
                        "limit": 20.0,
                        "numberPhases": 1,
                        "startPeriod": 0
                    }
                ],
                "duration": 86400,
                "id": 0,
                "minChargingRate": 0.0,
                "startSchedule": "2024-06-13T00:00:00.000Z"
            }
        ],
        "id": 1,
        "recurrencyKind": "Daily",
        "stackLevel": 1
    },
    "evseId": 1
}
with messageId: 197d7fa0-8aba-4135-bb0f-9fcbe3c2d280
2024-06-13 16:28:32.926104 [WARN] ocpp:OCPP201    module::OCPP201::ready()::<lambda()> :: Received a new Charging Schedules from the CSMS or another actor.
2024-06-13 16:28:32.926363 [INFO] ocpp:OCPP201     :: ProfileId #1 Kind: Absolute
2024-06-13 16:28:32.926639 [INFO] ocpp:OCPP201     :: #1 find_period_at> 2024-06-13T00:00:00.000Z
2024-06-13 16:28:32.926950 [INFO] ocpp:OCPP201     ::    find_period_at>        start_time> 2024-06-13T16:28:32.926Z
2024-06-13 16:28:32.927014 [INFO] ocpp:OCPP201     ::    find_period_at> period_start_time> 2024-06-13T00:00:00.000Z
2024-06-13 16:28:32.927057 [INFO] ocpp:OCPP201     ::    find_period_at>   period_end_time> 2024-06-14T00:00:00.000Z
2024-06-13 16:28:32.927286 [INFO] ocpp:OCPP201     :: PeriodDateTimePair>  period: {
    "limit": 20.0,
    "numberPhases": 1,
    "startPeriod": 0
} end_time: 2024-06-14T00:00:00.000Z
2024-06-13 16:28:32.927585 [INFO] ocpp:OCPP201     :: period.has_value() limit = 4600
2024-06-13 16:28:32.927671 [INFO] ocpp:OCPP201     :: period.has_value() stackLevel = 4600
2024-06-13 16:28:33.018306 [ERRO] ocpp:OCPP201    void ocpp::v201::ChargePoint::handle_set_charging_profile_req(ocpp::Call<ocpp::v201::SetChargingProfileRequest>) :: Received profile validity: Validsetting response to {
    "status": "Accepted"
}
```

</details>

> Plugged in the car again, and got max power of 4600 W, with 230V and 6.6A

<details>
<summary>Got the same result once started charging using new profile</summary>

```
2024-06-13 16:33:53.809243 [DEBG] iso15118_car    pybind11_init_everestpy(pybind11::module_&)::<lambda(const std::string&)> :: Decoded message (ns=urn:iso:15118:2:2013:MsgDef): {"V2G_Message":{"Header":{"SessionID":"E8875BBEF62E2EFF"},
"Body":{"ChargeParameterDiscoveryRes":{"ResponseCode":"OK",
"EVSEProcessing":"Finished",
"SAScheduleList":{"SAScheduleTuple":[{"SAScheduleTupleID":1,
"PMaxSchedule":{"PMaxScheduleEntry":[{"RelativeTimeInterval":{"start":0,
"duration":86400},
"PMax":{"Multiplier":0,
"Unit":"W",
"Value":4600}}]}}]},
"AC_EVSEChargeParameter":{"AC_EVSEStatus":{"NotificationMaxDelay":0,
"EVSENotification":"None",
"RCD":false},
"EVSENominalVoltage":{"Multiplier":-1,
"Unit":"V",
"Value":2300},
"EVSEMaxCurrent":{"Multiplier":-1,
"Unit":"A",
"Value":66}}}}}}
```

</details>

**Pull request merged**
